name: Run Detekt and unit tests

on: push

jobs:
  run_detekt_and_unit_tests:
    name: Run Detekt and unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout source code
        uses: actions/checkout@v2.3.2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt on CoroutineTemplate
        working-directory: ./CoroutineTemplate
        run: ./gradlew detekt

      - name: Run Detekt on RxJavaTemplate
        working-directory: "./RxJavaTemplate[DEPRECATED]"
        run: ./gradlew detekt

      - name: Archive Detekt reports on CoroutineTemplate
        uses: actions/upload-artifact@v2
        with:
          name: DetektReportsCoroutine
          path: CoroutineTemplate/build/reports/detekt/

      - name: Archive Detekt reports on RxJavaTemplate
        uses: actions/upload-artifact@v2
        with:
          name: DetektReportsRxJava
          path: RxJavaTemplate\[DEPRECATED\]/build/reports/detekt/

      - name: Run unit tests and Jacoco on RxJavaTemplate
        working-directory: "./RxJavaTemplate[DEPRECATED]"
        run: ./gradlew jacocoTestReport

      - name: Archive code coverage reports on RxJavaTemplate
        uses: actions/upload-artifact@v2
        with:
          name: CodeCoverageReportsRxJava
          path: |
            RxJavaTemplate\[DEPRECATED\]/app/build/reports/jacoco/jacocoTestReport/
            RxJavaTemplate\[DEPRECATED\]/data/build/reports/jacoco/jacocoTestReport/
